### ISSUE TITLE
Database- job collection 

### ISSUE THREAD

**Issue by Yasir19** [Yasir19/smart-home#4]
job collection must contain 
* ID 
* project description 
* Phone number 
* Project address 
* Project date 
* Project ETC 
* Project Cost (cost will be estimated when the user create the job, once the user approve the job, the cost must be changed based on the approved agreement)

**Comment by mgall13** [comment]
Make it a subdocument of the User and Contractor.

**Comment by mgall13** [comment]
Working on Project routes.
